//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librayry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.CallCardDetails = new HashSet<CallCardDetail>();
        }
    
        public string BookId { get; set; }
        public string BookName { get; set; }
        public string Description { get; set; }
        public string Language { get; set; }
        public string Author { get; set; }
        public string Publisher { get; set; }
        public int Quantity { get; set; }
        public int RemainQuantity { get; set; }
        public System.DateTime DateAdd { get; set; }
        public decimal Price { get; set; }
        public int CategoryId { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallCardDetail> CallCardDetails { get; set; }
    }
}
