//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Librayry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CallCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CallCard()
        {
            this.CallCardDetails = new HashSet<CallCardDetail>();
        }
    
        public int CallCardId { get; set; }
        public int UserId { get; set; }
        public int Quantity { get; set; }
        public System.DateTime BorrowDate { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CallCardDetail> CallCardDetails { get; set; }
        public virtual User User { get; set; }
    }
}
